# Generated by Django 4.0.2 on 2022-02-22 20:26

import core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='full name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='about author')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='about book')),
                ('pages', models.PositiveIntegerField(default=10)),
                ('language', models.CharField(blank=True, default='English', max_length=100, null=True)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[core.utils.validate_published_year])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cover', models.ImageField(default='ebook_pictures/default.png', upload_to=core.utils.book_cover_upload)),
                ('slug', models.SlugField(unique=True)),
                ('pdf', models.FileField(upload_to=core.utils.pdf_upload, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='book.Genre')),
            ],
        ),
    ]
